api_platform:
    title: 'Faume.co API'
    version: 3.0.0
    show_webby: false
    eager_loading:
        enabled: false
    enable_re_doc: false
    swagger:
        api_keys:
            brand_id:
                name: X-Brand-ID
                type: header
            access_token:
                name: Authorization
                type: header
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']
            purger: 'api_platform.http_cache.purger.varnish.ban'
        public: true
    defaults:
        stateless: true
        cache_headers:
            max_age: 0
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_items_per_page: 10
        pagination_maximum_items_per_page: 50
        pagination_client_items_per_page: true
        normalization_context:
            skip_null_values: false
        collectDenormalizationErrors: true
        order:
            createdAt: DESC
    keep_legacy_inflector: false
    use_symfony_listeners: true
    path_segment_name_generator: api_platform.metadata.path_segment_name_generator.dash
